### ISSUE TITLE
Where did the benchmark MIDI files come from?

### ISSUE THREAD

**Issue by yamadapc** [negamartin/midly#17]
Hey mate great job with this crate!

I have been working on [augmented-midi](https://beijaflor.io/blog/05-2022/midi-parsing/) for fun and hadn't really looked into this library before.

My parser/serializer uses `nom`, but since performance is fun, I ran the benchmarks in this repository and got the following results:
```
parsing file "../test-asset/Levels.mid" (2 KB)
  midly: 5 tracks in 50 iters / min 0.01 / avg 0.02 / max 0.44
  augmented-midi: 5 tracks in 50 iters / min 0.01 / avg 0.01 / max 0.01

parsing file "../test-asset/ClementiRewritten.mid" (4 KB)
  midly: 3 tracks in 50 iters / min 0.06 / avg 0.77 / max 8.14
  augmented-midi: 3 tracks in 50 iters / min 0.02 / avg 0.24 / max 3.08

parsing file "../test-asset/SysExTest.mid" (0 KB)
  midly: 3 tracks in 50 iters / min 0.01 / avg 0.01 / max 2.17
  augmented-midi: parse error

parsing file "../test-asset/Sandstorm.mid" (78 KB)
  midly: 19 tracks in 50 iters / min 0.1 / avg 1.38 / max 9.6
  augmented-midi: 19 tracks in 50 iters / min 0.21 / avg 0.32 / max 2.78

parsing file "../test-asset/Pi.mid" (24650 KB)
  midly: 30 tracks in 50 iters / min 23.32 / avg 33.24 / max 156.62
  augmented-midi: 30 tracks in 50 iters / min 79.74 / avg 96.66 / max 141.69

parsing file "../test-asset/CrabRave.mid" (53 KB)
  midly: 14 tracks in 50 iters / min 0.17 / avg 1.92 / max 10.47
  augmented-midi: 14 tracks in 50 iters / min 0.16 / avg 0.27 / max 2.4

parsing file "../test-asset/PiDamaged.mid" (64 KB)
  midly: 3 tracks in 50 iters / min 0.18 / avg 0.62 / max 4.8
  augmented-midi: parse error

parsing file "../test-asset/Beethoven.rmi" (90 KB)
  midly: 15 tracks in 50 iters / min 0.2 / avg 1.01 / max 8.57
  augmented-midi: parse error

parsing file "../test-asset/Clementi.mid" (4 KB)
  midly: 3 tracks in 50 iters / min 0.04 / avg 0.1 / max 0.55
  augmented-midi: 3 tracks in 50 iters / min 0.02 / avg 0.03 / max 0.1

parsing file "../test-asset/RiverFlowsInYou.mid" (6 KB)
  midly: 2 tracks in 50 iters / min 0.03 / avg 0.16 / max 1.12
  augmented-midi: 2 tracks in 50 iters / min 0.02 / avg 0.03 / max 0.08
```

I fixed the nº of iterations at 50.

There are some parse errors I can look into, but the most interesting for me is:
```
parsing file "../test-asset/Pi.mid" (24650 KB)
  midly: 30 tracks in 50 iters / min 23.32 / avg 33.24 / max 156.62
  augmented-midi: 30 tracks in 50 iters / min 79.74 / avg 96.66 / max 141.69
```

Initially my parser was around 5 times worse for this large file (min ~100), which was improved by trying to pre-allocate the `Vecs`.

I suppose it will be slower for varied reasons due to this being handwritten, but it's a fun exercise to understand why exactly.

Is the 25MB MIDI file just lots of pitch-wheel events? There might be a difference in behaviour (when the 14bit nº is converted into 16bit or otherwise).

Cheers

**Comment by kovaxis** [comment]
Hello! Sorry for the late reply.

About the question in the title, the benchmark results come from the `benchmark` crate that is present in the root of this repo, although I believe you already know this.

I do not know what events the `Pi.mid` file consists of exactly, but it's probably a lot of NoteOn events since it is a black MIDI ([this one](https://www.youtube.com/watch?v=Ay8vzCHkgEk) to be precise).

About the exact reason why `midly` is faster in this regard, it's almost certainly because `midly` uses multiple threads to parse.

You got some pretty neat performance results, congratulations! Do you happen to know how are you getting better performance than `midly`?

**Comment by yamadapc** [comment]
Thanks for the response! I don't think I had noticed `rayon` initially.

For the cases performance is better, I'd imagine it's due to avoiding memory allocation. The crate is just using `nom` otherwise.

Even limiting the number of threads `midly` seems much faster for that 25MB file (plus there are a few parse errors I need to fix still).

**Comment by kovaxis** [comment]
Hmmm that's strange, I believe both crates do the same amount of allocation. Maybe because you are using generics all throughout the parser the compiler gets to inline more functions.

The difference in speed for the larger file might come from the size of the memory representation. `TrackEvent` might be smaller than `MIDITrackEvent` due to how the types are defined. Just a hunch though.
