### ISSUE TITLE
Static SMF

### ISSUE THREAD

**Issue by nobbele** [negamartin/midly#22]
Rather than clearing bytes, why is MetaMessage not composed of Cow so make_static can just turned them into the owned variants?

**Comment by kovaxis** [comment]
Because it would have a non-zero cost for users that are not using static MIDI files. `Cow<[u8]>` is one `usize` larger than `&[u8]`, and requires a branch on every use.

There are some alternatives, for example the following custom `Cow` is only two `usize`s in a 64-bit platform:

```rust
struct Bytes {
    ptr: NonNull<u8>,
    len: u32,
    cap: u32,
}
```

Implementing something like this would be a breaking change. I've simply not found it compelling enough to write.

I'm curious, are you in a situation where you want a static SMF with data in `MetaMessage`?
