### ISSUE TITLE
impl std::error::Error for midly::Error

### ISSUE THREAD

**Issue by Boscop** [negamartin/midly#6]
Please impl `std::error::Error` for `midly::Error` so that it can be used with error convenience crates like `anyhow` :)

**Comment by kovaxis** [comment]
Yeah, when first writing `midly` the whole ecosystem was shaped around `failure`, but now everyone seems to have moved to `std::error::Error`.

The only issue I see with `std::error::Error` is that it is in `std`, not in `core`.
Guess that's not as much of a problem since `anyhow` support `no_std` though?

Anyways this is a breaking change, so it's pending for `0.5`.
Since failure implements `Fail` automatically for types that implement `std::error::Error`, I think it would be ok to implement `std::error::Error` instead of `Fail` when `std` is available (although that would throw backtraces away completely, it's not like anybody uses them :P).

Thanks for bringing this up!

**Comment by Boscop** [comment]
Thanks! Yeah, `std::error::Error` was fixed in the meantime..
And failure is deprecated now: https://www.reddit.com/r/rust/comments/gcbcew/notice_failure_is_deprecated/

The nice thing about `thiserror` is that it doesn't leak into the public API of the crate that's using it. It just exposes the error type as being `std::error::Error`, so it doesn't force the user to use a specific error handling crate.

**Comment by kovaxis** [comment]
Done in `0.5`.
