### ISSUE TITLE
Decouple write feature from std

### ISSUE THREAD

**Issue by kovaxis** [negamartin/midly#9]
Writing is possible without `std`, but it's currently unavailable without it.
One could imagine embedded devices that need to generate MIDI, so it'd be great to support that use-case.

**Comment by PieterPenninckx** [comment]
I'm in favor of decoupling. I've added `midly` as a dependency to a crate of mine (not specific for embedded) and I don't need parallelization. I have to keep the `std` feature for `midly` for writing, but this means adding `rayon` as a dependency as well, making the crate more heavy-weight.

**Comment by kovaxis** [comment]
Done in `0.5`.

Also, `parallel` and `std` are now separate features, so you can now just disable multithreading while keeping integration with `std`.

Just curious, but which crate exactly? I'm interested in real-world usage of the library.

**Comment by PieterPenninckx** [comment]
I'm using it in [`rsynth`](https://github.com/PieterPenninckx/rsynth/). This is not really "real-world usage" since `rsynth` is just an abstraction layer. I'm using `rsynth` together with the [`tdpsola`](https://crates.io/crates/tdpsola) crate to create an (unpublished) application that re-tunes a sound with a constant pitch to the pitches from the notes from a midi file.
